### ISSUE TITLE
Navit initial pitch problem

### ISSUE THREAD

**Issue by dbemowsk** [droundy/navit-config#1]
So I was going to post this in the navit-project.org forums, but I can't create an account there.  It says I don't have permissions.  I don't know if this is the right place to post this, but I couldn't find any other place to post this.

Anyway, I am running navit on a Raspberry PI 4B 2GB and my issue is that when I attempt to set a pitch value in the navit tag, the map always shows inverted and at the same high pitch (shows a horizon) no matter the value I set for pitch > 0.  I have a button set to switch between 2D and 3D view, but that starts in 2D view and I want it to start in 3D view.  I don't want to have to hit the 3D button every time navit starts.

**Comment by droundy** [comment]
I haven't used navit for years, so this isn't a helpful place to post an issue.
